package:
    name: snapshot
    version: 1.2.0
source:
#    git_tag: 0.9.1
#    git_url: https://github.com/channelaccess/snapshot.git
    path: ..

requirements:
    build:
        - python
        - setuptools
        - pyqt
    run:
        - python
        - pyqt

build:
  entry_points:
    - snapshot = snapshot.snapshot:main

about:
    home: https://github.com/channelaccess/snapshot
    summary: "Tool to save and restore EPICS channels."
