package:
    name: snapshot
    version: 2.0.0
source:
#    git_tag: 0.9.1
#    git_url: https://github.com/channelaccess/snapshot.git
    path: ..

requirements:
    build:
        - python==3.5
        - setuptools
        - pyqt==4
    run:
        - python==3.5
        - pyqt
        - pyepics
        - numpy


build:
  entry_points:
    - snapshot = snapshot.snapshot:main

about:
    home: https://github.com/paulscherrerinstitute/snapshot
    summary: "Tool to save and restore EPICS channels."
