package:
    name: snapshot
    version: v0.0.2
source:
    git_tag: v0.0.2
    #git_url: https://git.psi.ch/cosylab/snapshot_tool.git
    git_url: /home/rvintar/workspace/CSL/SaveRestore/git/snapshot_tool

requirements:
    build:
        - python
        - setuptools
        - pyqt
    run:
        - python
        - pyqt

build:
  entry_points:
    - snapshot = snapshot.snapshot:main

about:
    home: https://github.psi.ch/cosylab/snapshot_tool
    summary: "Tool to save and restore EPICS channels."
